#!/bin/bash
#
# hzclish - Hubzilla (ex Red Matrix) cli bash script.
# Version 1.2
# Source: https://notabug.org/uzver/hzclish
#
# License: WTFPL2 http://wtfpl2.com/
# uzver(at)protonmail.ch
#
# Deps: curl, jq, markdown or pandoc or discount, grep, sed, awk, tr, mkdir, mktemp, rm, wc


dotdir="${HOME}/.hzclish"
verbose=0
ssl=1
markdown="markdown"
useragent='Mozilla/5.0 (Windows NT 6.1; rv:41.0) Gecko/20100101 Firefox/41.0'

# FUNCTIONS

USAGE(){
    exec=$(basename "$0"); [[ "$exec" ]] || exec="${0##*/}"
    cat << EOF
  $exec - CLI bash wrapper script for the Hubzilla (Red Matrix) API.

  USAGE: $exec [OPTIONS] [-u LOGIN:DOMAIN[:PASSWORD]] [<<<"MESSAGE"]
    
  OPTIONS:
    -c config                  Specify config file
                                (you can use different configs for different accounts)
    -d config                  Specify config file and set it as default auth
    -D                         Delete config and cookie files
    -g ID                      Get post of given ID
    -h, --help                 Show this help
    -i                         Post from stdin
    -m <str>                   Set markdown engine (overwrites: -P)
    -p                         Post message
    -P                         Use pandoc instead of markdown
                                (short for: -m "pandoc -f markdown -t html")
    -q                         Less verbose successful printing
    -r                         Renew auth token
    -s                         Set authentification (save login, password)
    -S yes|no                  Use or not https (default: yes) (useful for inline auth: -u)
    -t                         Convert very last line with hashtags of message to categories,
                                and post with both same hashtags and categories
    -T                         Convert very last line with hashtags of message to categories,
                                and drop hashtags, post only with categories
    -u LOGIN:DOMAIN[:PASSWORD] Specify auth inline, e.g.: "inbox@example.com:hubdomain.com:password", or:
        "channel@hubdomain.com:password", or:
        "channel@hubdomain.com"
                                (use it if you do not want to save auth)
                                (implies not use with: -c, -D, -r, -s)
    -v                         Verbose mode
    
    Notice: For now length of message limited by bash variable size limit.

  EXAMPLES:
    Set authentification to config file:
      $exec -vs
     or to custom place:
      $exec -vc myConfig -s                    # save in "$dotdir"
      $exec -vc ~/myConfig -s                  # save in home directory
     or to custom place and set it default:
      $exec -vd myNewDefaultConfig -s          # save in "$dotdir"
      $exec -vd ~/myNewDefaultConfig -s        # save in home directory

    Post message:
      $exec
      $exec -vp
      $exec -c myConfig                        # with custom config
      $exec -d myNewDefaultConfig              # with set default config
    Post message from stdin:
      $exec <<<"Hello world!"
      echo "Hello world!" | $exec
      cat myPost.md | $exec
      $exec <<<"Hello world!"
      $exec <<<"Hello world!"

    Read post by id:
      $exec -g 1234567
      $exec -qg 1234567
      $exec -c myConfig -g 1234567             # with custom config
      $exec -d myNewDefaultConfig -g 1234567   # with set default config
EOF
}

CONFIG(){
    # Check for config file and create it if it does not exist
    if ! (($custconfig)); then
        confdir="$dotdir"
        [[ -f "${confdir}/defaultconfig" ]] && source "${confdir}/defaultconfig"
    else
        ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""Using config: $config""\e[m"
        [[ -f "$config" ]] && confdir=$(dirname "$config")
        [[ -d "$confdir" ]] || confdir="$dotdir"
        if [[ -f "$config" ]]; then
            true
        else
            if [[ -f "${confdir}/$config" ]]; then
                config="${confdir}/$config"
            elif [[ -f "${confdir}/${config}.config" ]]; then
                config="${confdir}/${config}.config"
            fi
        fi
# echo confdir "$confdir"
# echo config "$config"
# exit
    fi
    if [[ -f "$config" ]]; then
        ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""Using config: $config""\e[m"
        # (($custconfig)) && confdir=$(dirname "$config")
        if (($setdefconf)); then
            ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""Setting default config: $config""\e[m"
            echo "config=\"$config\"">"${confdir}/defaultconfig"
        fi
    else
        mkdir -p "$confdir" && chmod 700 "$confdir"
        echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "No config file found! Let's create one"
        read -p "Enter hub domain (example.com): " domain
        domain=$(echo "${domain%/*}" | sed 's|^[[:space:]]*https\?://||g')
        if ! (($sslsetted)); then
            IFSSL(){
                read -p "Does your hub use SSL? (y/n) " sslresponse
            }
            IFSSL
            if [[ $sslresponse == [Nn] ]]; then
                ssl=0
                hub="http://$domain"
            elif [[ $sslresponse == [Yy] ]]; then
                ssl=1
                hub="https://$domain"
            else
                echo "Response not valid, please answer y or n"
                IFSSL
            fi
        fi
        if (($ssl)); then
            hub="https://$domain"
        else
            hub="http://$domain"
        fi
        read -p "Enter login e-mail: " login
        read -p "Enter nickname (channel nickname) (or leave blank): " channel
        if [[ "$channel" ]]; then
            zid="${channel}@$domain"
        elif [[ "$login" ]]; then
            zid="${login}@$domain"
        fi
        if ! [[ "$login" ]]; then
            echo 'Please specify login'
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exit 1
        fi
        if ! (($custconfig)); then
            config="${confdir}/${zid}.config"
        fi
        if [[ ! -f "${confdir}/defaultconfig" || "$(cat "${confdir}/defaultconfig" | wc -m)" == 0 ]] || (($setdefconf)); then
            ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""Setting default config: $config""\e[m"
            echo "config=\"$config\"">"${confdir}/defaultconfig"
        fi
{
cat << EOF
hub="$hub"
login="$login"
channel="$channel"
zid="$zid"
useragent="$useragent"
cookie="\${zid}.cookie"
EOF
}>"$config"
        chmod 600 "$config"
        if ! (($quiet)) && (($verbose)); then
            echo -e "\e[0;36m""These variables have been saved to ${config}:""\e[m"
            echo -e "\e[0;36m"; cat "$config"; echo -e "\e[m"
        fi
    fi
    source "$config"
    # scookie="${confdir}/${zid}.cookie"
    [[ -f "${confdir}/$cookie" ]] || (touch "${confdir}/$cookie" && chmod 600 "${confdir}/$cookie")
}

PASSWORD(){
unset password
if [[ "$config" ]] && [[ "$(grep 'password=' "$config")" ]]; then
    source "$config"
else
    echo ""
    prompt="What is your password?: "
    while IFS= read -p "$prompt" -r -s -n 1 char
    do
        if [[ $char == $'\0' ]]; then
            break
        fi
            prompt='*'
            password+="$char"
    done
    echo -e "\n"
fi
}

SETAUTH(){
    CONFIG
    source "$config"
    if [[ "$(grep 'token=.' "$config")" ]]; then
        echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Script appears to be registered previously"
        echo "Use -d option to delete auth and then -s to try again"
        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
        exit 1
    else
        if ! [[ "$password" ]]; then
            echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "This will be the only time you will be asked for your password"
            echo "Your password will be stored plain in config file"
            PASSWORD
        fi
        sed -i '/password=/d' "$config"
        echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
        if (($verbose)); then
            echo -e "\e[0;36m""Password have been saved to $config""\e[m"
        fi
        
        source "$config"
        echo "Getting token..."
        getauth=$(curl -ksSi --trace-ascii - -u "$login":"$password" \
         -H "User-Agent: $useragent" \
        "${hub}/api/account/verify_credentials" \
         --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie")
        token=$(echo "$getauth"|sed -n 's/^.*Authorization: Basic \(.*\)/\1/p1')

        # unset getauth
        if [[ "$token" ]]; then
            sed -i '/token=/d' "$config"
            echo "token=\"${token}\"">>"$config"
            # unset token
            if (($verbose)); then
                echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Token saved"
            fi
        else
            echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Getting token failed. Check/set your login/password/connection"
(($verbose)) && echo -e '\e[37;31m'"\e[1m[post]\e[0m" && echo "$getauth"
unset getauth
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exitstatus=1
        fi

        local error=''
        error=$(echo "$getauth" | grep -iom1 '^This api requires login')
        [[ "$error" ]] || error=$(echo "$getauth" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
        if [[ "$error" ]]; then
            [[ "$token" ]] && echo 'but'
            unset token
            echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
            echo "Check/set your login/password/server and try again"
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exitstatus=1
        fi

        if (($exitstatus)); then
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exit $exitstatus
        fi
    fi
}

RETOKEN(){
    CONFIG
    source "$config"
    while [[ ! $retokened ]]; do
        if ! (($quiet)) && (($verbose)); then
            echo -e "\e[0;36m""Getting new token...""\e[m"
        fi
        if ! [[ "$password" ]]; then
            PASSWORD
        fi
        getauth=$(curl -ksSi --trace-ascii - -u "$login":"$password" \
         -H "User-Agent: $useragent" \
        "${hub}/api/account/verify_credentials" \
         --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie")
        body=$(echo -n "$getauth"|grep -iom1 '{\".*[^\]\(["}]\|\]\)}')
        [[ "$body" ]] || body=$(echo -n "$getauth"|grep -i 'error')
        unset password
        token=$(echo "$getauth"|sed -n 's/^.*Authorization: Basic \(.*\)/\1/p1')

        # unset getauth
        if [[ "$token" ]]; then
            sed -i '/token/d' "$config"
            echo "token=\"${token}\"">>"$config"
            # unset token
            if (($verbose)); then
                echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Token saved"
            fi
        else
            echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Getting new token failed. Check/set your login/password/server"
(($verbose)) && echo -e '\e[37;31m'"\e[1m[post]\e[0m" && echo "$getauth"
unset getauth
            # (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exitstatus=1
        fi

        local error=''
        error=$(echo "$getauth" | grep -iom1 '^This api requires login')
        [[ "$error" ]] || error=$(echo "$getauth" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
        if [[ "$error" ]]; then
            [[ "$token" ]] && echo 'but'
            unset token
            echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
            (($verbose)) && [[ "$body" ]] && echo -en "\e[0;31m"; echo -n "$body"; echo -e "\e[m"
            echo "Check/set your login/password/server"
            # (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exitstatus=1
        fi

        if (($exitstatus)); then
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exit $exitstatus
        fi
        ((retokened++))
    done
}

GETPOST(){
    if ! (($inlineauth)); then
        CONFIG
        source "$config"
        unset password
    fi
    if [[ "$1" ]]; then
        local pid="$1"
    else
        echo 'Please specify the post id'
        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
        exit 1
    fi
    [[ "$2" == 'urlonly' ]] && local urlonly=1
    local post=''
    GETPOSTINIT(){
        if (($inlineauth)); then
            ! [[ "$password" ]] && PASSWORD
            (($verbose)) && echo -e "\e[0;36m""Getting post $pid...""\e[m"
            post=$(
                curl -ksSi -u "$login":"$password" \
                    -H "User-Agent: $useragent" \
                    -H "Content-Type: application/json" \
                    -H 'Accept: application/json' \
                    "${hub}/api/statuses/show.json?id=$pid")
            unset password
        else
            (($verbose)) && echo -e "\e[0;36m""Getting post $pid...""\e[m"
            post=$(
                curl -ksSi \
                    -H "Authorization: Basic $token" \
                    -H "User-Agent: $useragent" \
                    -H "Content-Type: application/json" \
                    -H 'Accept: application/json' \
                    "${hub}/api/statuses/show.json?id=$pid" \
                    --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie")
            unset token
        fi
        postbody=$(echo -n "$post"|grep -iom1 '{\".*[^\]\(["}]\|\]\)}')
        mid=$(echo -n "$postbody"|jq -r '.message_id')
        posturl=$(echo -n "$postbody"|jq -r '.url')
        posturl2="$(echo -n "$posturl"|sed 's|^.*\(https\?://[^/]\+\)/.*|\1|')/display/$mid"
        if ! (($urlonly)); then
            username=$(echo -n "$postbody"|jq -r '.user.screen_name')
            userurl=$(echo -n "$postbody"|jq -r '.user.url')
            userhub=$(echo "$userurl"|sed 's|^.*https\?://\([^/]\+\)/.*|\1|')
            posttxt=$(echo -n "$postbody"|jq -r '.text')
        fi
    }
    GETPOSTINIT
    local error=''
    error=$(echo "$post" | grep -iom1 '^This api requires login')
    [[ "$error" ]] || error=$(echo "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
    if [[ "$error" ]]; then
        if [[ $retokened != 1 ]] && [[ $inlineauth != 1 ]]; then
            if ! (($quiet)); then
                # echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
                # echo -e '\e[37;32m'"\e[1m[warning] \e[0m" "$error"
                echo -en "\e[0;33m[warning] \e[m"; echo "$error"
                echo "Error or invalid token, requesting new one..."
            fi
            RETOKEN
            GETPOSTINIT
            local error=''
            error=$(echo "$post" | grep -iom1 '^This api requires login')
            [[ "$error" ]] || error=$(echo "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
            if [[ "$error" ]]; then
                echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
                echo "Can't get post due authorization issue"
                echo "Check/set your login/password/server and try to get post again"
                (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
                exit 1
            fi
        else
            echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
            echo "Can't get post due authorization issue"
            echo "Check/set your login/password/server and try to get post again"
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exit 1
        fi
    fi

    if [[ "$mid" ]]; then
        if ! (($urlonly)); then
            echo -e "\e[0;36m""${username}@${userhub}:""\e[m\n"
            echo "$posttxt"
            if ! (($quiet)); then
                echo -e "\n\e[0;36m""post url: $posturl2""\e[m"
            fi
        else
            echo -e "\n\e[0;36m""$posturl2""\e[m"
        fi
            
    else
        echo -e '\e[37;31m'"\e[1m[error]\e[0m" "No post returned, please try again or give up"
(($verbose)) && echo -e '\e[37;31m'"\e[1m[post]\e[0m" && echo "$post"
        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
        exit 1
    fi
}

POST(){
    if ! (($inlineauth)); then
        CONFIG
        source "$config"
        unset password
    fi
    if ! (($hasmsg)); then
        local postfile=$(mktemp /tmp/hzpost.XXXXXX)
        local message=$(mktemp /tmp/hzmessage.XXXXXX)
    else
        local postfile="$postfile"
        local message="$message"
# echo HAS MESSAGE
# echo
# echo verbose "$verbose"
# echo hasmsg "$hasmsg"
# echo postfile "$postfile"
# echo message "$message"
# echo tagline "$tagline"
# echo tags "$tags"
# echo catline "$catline"
# cat "$message"
# exit
    fi
    chmod 600 "$postfile" "$message"
    local post=''
    local pid=''
    POSTINIT(){
        if ! (($hasmsg)); then
            if ! [[ -t 0 ]] || (($stdin)); then
                eval 'stdin=$(cat); echo "$stdin"' >"$message"
            else
                $EDITOR "$message"
            fi
            msglength=$(cat "$message" | wc -m)
            if ! (($msglength)); then
                echo -e '\e[37;31m'"\e[1m[error]\e[0m" "The message is empty. Not posting message"
                echo "Not deleting the file \"$message\" in case it is not empty"
                /bin/rm -f "$postfile"
                (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
                exit 1
            fi
            ## Remove leading blank lines
            sed -i '/./,$!d' "$message"
        fi
        if [[ ! "$tagline" ]]; then
            tagline=$(tail -n 1 "$message" | grep -io '^[[:space:]]*\?\#.*\?')
             [[ "$tagline" ]] && hastagline="$tagline"
            ! (($catonly)) && tags=$(echo "$tagline" | sed 's|^[[:space:]]*||; s|,||g')
        fi
        if [[ ! "$catline" ]]; then
            catline=$(head -n 1 "$message" | grep -iom1 '^[[:space:]]*\?\*.*\?')
            [[ "$catline" ]] && hascatline=1
            (($tagtocat)) && catline=$(echo "$tagline" | sed 's|^[[:space:]]*\?\#|\*|g; s|[[:space:]]*\?\#| \*|g')
        fi
        catsarr=($(echo "$catline" | sed 's|[\*]| |g; s|^[[:space:]]*||; s|,||g; s/\"/\\"/g'))
        local category=''
        for c in "${catsarr[@]}"; do category+="${c},"; done
        # (($catonly)) && tagline='' && tags=''
# echo verbose "$verbose"
# echo hasmsg "$hasmsg"
# echo postfile "$postfile"
# echo message "$message"
# echo tagline "$tagline"
# echo tags "$tags"
# echo catline "$catline"
# echo catsarr "${catsarr[@]}"
# echo category "$category"
# cat "$message"
# echo
        msg=$(cat "$message")
# echo msg "$msg"
# echo
# echo
        if ! (($catonly)); then
            if [[ "$tagline" || "$hastagline" ]]; then
                msg=$(echo "$msg" | awk -v tl="$tagline" -F "$tagline" '{print $1}')
            fi
        else
            tagline='' && tags=''
            [[ "$hastagline" ]] && msg=$(echo "$msg" | awk -v tl="$hastagline" -F "$hastagline" '{print $1}')
        fi
# echo msg "$msg"
# echo hasmsg $hasmsg
# echo hastagline $hastagline
# echo hascatline $hascatline
# echo catline "$catline"
# exit
        if ! (($hasmsg)) && ! (($tagtocat)) && (($hascatline)); then
            [[ "$catline" ]] && msg=$(echo "$msg" | awk -v cl="$catline" '$0 == cl {i=1;next};i && i++ <= 999')
        fi
        title=$(echo "$msg" | head -n 1 | grep -iom1 '^[[:space:]]*\?\#[[:space:]]\+.*\?' | sed 's/\"/\\"/g; s/^[[:space:]]*\?\#[[:space:]]\+//g')
        [[ "$title" ]] && msg=$(echo "$msg" | sed 1d)
# echo hasmsg $hasmsg
# echo hastagline $hastagline
# echo hascatline $hascatline
# echo message "$message"
# echo tagline "$tagline"
# echo tags "$tags"
# echo catline "$catline"
# echo catsarr "${catsarr[@]}"
# echo title "$title"
# echo -n 'message '; cat "$message"; echo 
# echo msg "$msg"
# exit
        [[ "$title" ]] && echo "title=\"$title\"">"$postfile"
        [[ "$category" ]] && echo "category=\"${category%,}\"">>"$postfile"
        if (($pandoc)); then
            markdown="pandoc -f markdown -t html"
        elif [[ "$mdexec" ]]; then
            markdown="$mdexec"
        fi
        htmlstatus=$(echo -n "$msg" | $markdown | sed 's/\"/\\"/g' | tr -d "\n"; [[ "$tags" ]] && echo "<br><br>$tags" | sed 's/\"/\\"/g' || echo "")
        [[ "$htmlstatus" ]] && echo "htmlstatus=\"$htmlstatus\"">>"$postfile"
# echo msg "$msg"
# exit
        source "$postfile"
# echo " export token='$token'"
# echo " export useragent='$useragent'"
# echo " export hub='$hub'"
# echo " export title='$title'"
# echo " export category='$category'"
# echo " export channel='$channel'"
# echo " export htmlstatus='$htmlstatus'"
# echo " export cookie='$cookie'"
# exit
        if (($inlineauth)); then
            ! [[ "$password" ]] && PASSWORD
            (($verbose)) && echo -e "\e[0;36m""Posting...""\e[m"
            post=$(curl -ksSi -u "$login":"$password" \
             -H "User-Agent: $useragent" \
             -X POST \
            -d "title=${title}&category=$category" \
            --data-urlencode "htmlstatus=$htmlstatus" \
            "$hub"/api/statuses/update)
            unset password
        else
            (($verbose)) && echo -e "\e[0;36m""Posting...""\e[m"
            post=$(curl -ksSi \
             -H "Authorization: Basic $token" \
             -H "User-Agent: $useragent" \
             -X POST \
            -d "title=${title}&category=${category}&channel=$channel" \
            --data-urlencode "htmlstatus=$htmlstatus" \
            "$hub"/api/statuses/update \
             --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie")
            unset token
        fi
# echo "$post"
# exit
        postbody=$(echo -n "$post"|grep -iom1 '{\".*[^\]\(["}]\|\]\)}')
        mid=$(echo -n "$postbody"|jq -r '.message_id')
        if [[ "$mid" ]]; then
            posturl=$(echo -n "$postbody"|jq -r '.url')
            posturl2="$(echo -n "$posturl"|sed 's|^.*\(https\?://[^/]\+\)/.*|\1|')/display/$mid"
        fi
        pid=$(echo -n "$postbody"|jq -r '.id')
        username=$(echo -n "$postbody"|jq -r '.user.screen_name')
        userurl=$(echo -n "$postbody"|jq -r '.user.url')
        userhub=$(echo "$userurl" | sed 's|^.*https\?://\([^/]\+\)/.*|\1|')
    }
    POSTINIT
    local error=''
    error=$(echo "$post" | grep -iom1 '^This api requires login')
    [[ "$error" ]] || error=$(echo "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
    if [[ "$error" ]]; then
        if ! (($retokened)) && ! (($inlineauth)); then
            if ! (($quiet)); then
                # echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
                # echo -e '\e[37;32m'"\e[1m[warning] \e[0m" "$error"
                echo -en "\e[0;33m[warning] \e[m"; echo "$error"
                echo "Error or invalid token, requesting new one..."
            fi
            RETOKEN
            POSTINIT
            local error=''
            error=$(echo "$post" | grep -iom1 '^This api requires login')
            [[ "$error" ]] || error=$(echo "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
            if [[ "$error" ]]; then
                echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
                echo "Can't post due authorization issue"
                echo "Check/set your login/password/server and try to post again"
                (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
                exit 1
            fi
        else
            echo -en '\e[37;31m'"\e[1m[error] \e[0m"; echo -en "\e[0;31m"; echo -n "$error"; echo -e "\e[m"
            echo "Can't post due authorization issue"
            echo "Check/set your login/password/server and try to post again"
            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
            exit 1
        fi
    fi
    
    if [[ "$mid" || "$pid" ]]; then
        if ! (($quiet)); then
            echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Message "$pid" posted"
            echo -en "\e[0;36m""post url: ""\e[m"
# (($verbose)) && echo -e '\e[37;32m'"\e[1m[post]:\n$post\e[0m"
        fi
        if  [[ "$mid" ]]; then
            echo -e "\e[0;36m""$posturl2""\e[m"
        else
            GETPOST "$pid" urlonly
        fi
        /bin/rm -f "$postfile" "$message"
    else
        echo -e '\e[37;31m'"\e[1m[error]\e[0m" "No post id returned, please try again or give up"
(($verbose)) && echo -e '\e[37;31m'"\e[1m[post]:\n"; echo -n "$post"; echo -e "\e[0m"
        echo "Message should still be saved in the file $message"
        /bin/rm -f "$postfile"
        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
        exit 1
    fi
}

# DELETE CONFIG & COOKIE
DELETE(){
        [[ "$config" ]] && source "$config" && unset password
    ! (($quiet)) && echo Deleting: cookie: "${confdir}/${zid}.cookie", config: "$config"
    [[ "$confdir" && "$zid" ]] && [[ -f "${confdir}/${zid}.cookie" ]] && /bin/rm -f "${confdir}/${zid}.cookie"
    [[ "$config" ]] && [[ -f "$config" ]] && /bin/rm -f "$config"
}

if [[ $# -lt 1 ]]; then
    exe=1
    POST
elif [[ "$1" == '--help' ]]; then
    USAGE
    exit 0
fi

# RUN OPTIONS
while getopts ":c:d:Dg:him:pPqrsS:tTu:v" OPTION
do
  case $OPTION in
    c)
      if [[ "$OPTARG" ]]; then
        config="$OPTARG"
        custconfig=1
      fi
      ;;
    d)
      if [[ "$OPTARG" ]]; then
        config="$OPTARG"
        custconfig=1
      fi
      setdefconf=1
      # echo "$config"
      ;;
    D)
      exe=1
      DELETE
      ;;
    g)
      exe=1
      pid="$OPTARG"
      GETPOST "$pid"
      # echo "$pid"
      ;;
    h)
      exe=1
      USAGE
      ;;
    i)
      stdin=1
      ;;
    m)
      mdexec="$OPTARG"
      ;;
    p)
      exe=1
      POST
      ;;
    P)
      pandoc=1
      ;;
    q)
      quiet=1
      ;;
    r)
      exe=1
      RETOKEN
      ;;
    s)
      exe=1
      SETAUTH
      ;;
    S)
      sslarg="$OPTARG"
      if [[ "$sslarg" ]]; then
        if [[ "$sslarg" == [nN][oO] ]]; then
          ssl=0
          sslsetted=1
        elif [[ "$sslarg" == [yY][eE][sS] ]];   then
          ssl=1
          sslsetted=1
        fi
      else
        ssl=1
        sslsetted=1
      fi
      ;;
    t)
      tagtocat=1
      ;;
    T)
      tagtocat=1
      catonly=1
      ;;
    u)
      if [[ "$OPTARG" ]]; then
        # "user@example.com:hubdomain.com:password"
        haspass=$(echo "$OPTARG" | awk -F':' '{print $3}')
        login="${OPTARG%%:*}"
        if [[ "$haspass" ]]; then
          domainandpass="${OPTARG#*:}"
          domain="${domainandpass%%:*}"
          password="${domainandpass#*:}"
          unset haspass
          unset domainandpass
        else
          domain="${OPTARG##*:}"
        fi
        if (($ssl)); then
          hub="https://$domain"
        else
          hub="http://$domain"
        fi
        zid=""
        inlineauth=1
      fi
      ;;
    v)
      verbose=1
      ;;
    \?)
      # echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "Invalid option: -$OPTARG" >&2
      echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "Invalid option" >&2
      (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
      exit 1
      ;;
    :)
      echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "Option -$OPTARG requires an argument" >&2
      (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
      exit 1
      ;;
  esac
done
shift $(($OPTIND -1))
# echo $exe; exit
## Post if no other functional commands was given
if ! (($exe)); then
  exe=1
  POST
fi

exit 0

### TODO:
# rewrite with Zot API (due currently won't works with fresh Huubzilla)
# read by mid
# message size limit (bash var)
# use keyring
# delete post
# comment post
# delete comment
# reshare post
# like, dislike
# attach image to post
# read post + comments
# notifications
# debug
# version option
# webdav get files
# more errors handle
# >&2